name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build ./flask_log_app --tag mtbitag/flask_log_app:v1
    - name: Push Image
      run: docker push mtbiTag/flask_log_app:v1
      
